// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ43R3PT8aF-uFLb2kDYH1KxPe9EkrXRE',
    appId: '1:197209413056:web:ea6b7f5c06b1ee56b22425',
    messagingSenderId: '197209413056',
    projectId: 'pharmdrive-fc231',
    authDomain: 'pharmdrive-fc231.firebaseapp.com',
    storageBucket: 'pharmdrive-fc231.appspot.com',
    measurementId: 'G-FR0ESLFPBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArVGXHNCez2kybegvci1aLU96w-aMQPfY',
    appId: '1:197209413056:android:98bfc0f27917c8a0b22425',
    messagingSenderId: '197209413056',
    projectId: 'pharmdrive-fc231',
    storageBucket: 'pharmdrive-fc231.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHouOen5JfTmQ84l2RvPjhBeqLu4-nueM',
    appId: '1:197209413056:ios:1ac978d767dc6ca5b22425',
    messagingSenderId: '197209413056',
    projectId: 'pharmdrive-fc231',
    storageBucket: 'pharmdrive-fc231.appspot.com',
    iosBundleId: 'com.example.pharmdriveV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHouOen5JfTmQ84l2RvPjhBeqLu4-nueM',
    appId: '1:197209413056:ios:5f9cee6a814525bab22425',
    messagingSenderId: '197209413056',
    projectId: 'pharmdrive-fc231',
    storageBucket: 'pharmdrive-fc231.appspot.com',
    iosBundleId: 'com.example.pharmdriveV1.RunnerTests',
  );
}
